# Generated by Django 4.2.5 on 2023-10-24 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_alter_comment_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='post_counter_annotated',
            field=models.IntegerField(default=0, editable=False),
            preserve_default=False,
        ),
    ]
