# Generated by Django 4.2.5 on 2023-10-24 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_topic_post_counter_annotated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='post_counter_annotated',
        ),
    ]
