# Generated by Django 4.2.5 on 2023-12-10 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='content',
        ),
    ]
