# Generated by Django 4.2.5 on 2023-12-10 19:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_photocontestsubmission_photo_contest_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocontestsubmission',
            name='photo_contest_entry',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
